# Generated by Django 4.2.3 on 2023-08-03 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
