version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    image: django_image
    container_name: backend_con
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - public-net
    depends_on:
      - postgres_db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: nuxt_image
    container_name: frontend_con
    ports:
      - "3000:3000"
      - "24678:24678"
    depends_on:
      - backend
    networks:
      - public-net
    # command: npm start
    command: npm run dev

  nginx:
    image: nginx:latest
    container_name: nginx_con
    depends_on:
      - frontend
    links:
      - frontend
    networks:
      - public-net
    ports:
      - "42080:80"
  
  postgres_db:
    image: postgres:15
    container_name: postgres_con
    restart: always
    ports:
      - "5432:5432"
    networks:
      - public-net


networks:
  private-net:
    driver: bridge
  public-net:
    driver: bridge