# Generated by Django 4.2.3 on 2023-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PG", "PENDING"),
                    ("SG", "SHIPPING"),
                    ("CD", "COMPLETED"),
                    ("CL", "CANCELED"),
                ],
                default="PG",
                max_length=2,
            ),
        ),
    ]
