### Get all product
GET http://localhost:8000/api/products/categories/
Content-Type: application/json


### Create a category
POST http://localhost:8000/api/products/categories/new/
Content-Type: application/json

{
    "name": "Chair"
}


### Create a product
POST http://localhost:8000/api/products/new/
Content-Type: application/json

{
    "title" : "Chair Product -2",
    "price": 20,
    "discount_price": 15,
    "total_stock": 5,
    "description": "product desc",
    "category" : 1
}


### Get a product
GET http://localhost:8000/api/products/1/
Content-Type: application/json