# Generated by Django 4.2.3 on 2023-07-16 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="image_url",
            new_name="image",
        ),
    ]
