# Generated by Django 4.2.3 on 2023-07-16 19:13

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="image1",
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.models.upload_to
            ),
        ),
    ]
