# Generated by Django 4.2.3 on 2023-07-16 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_image_product_image1_product_image2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="desc",
            new_name="description",
        ),
    ]
